
name: Main Angular Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: firstCode/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: firstCode

      - name: Build Angular
        run: npm run build -- --output-mode=static --base-href=/visualFrontend/
        working-directory: firstCode
